# Basic configuration file for a A2RCHI deployment
# with a chat app interface, a QA pipeline, and
# a ChromaDB instance for document storage.
# The LLM is used through an existing Ollama server.
#
# run with:
# a2rchi create --name my-a2rchi-ollama --config examples/deployments/basic-ollama/config.yaml --services chatbot --hostmode

name: my_a2rchi

services:
  chat_app:
    trained_on: "My data"
    port: 7868
    external_port: 7868
  chromadb:
    # running in hostmode, want to avoid taking the default chromadb port (8000) since it's usually taken by host already
    chromadb_port: 8003
    chromadb_external_port: 8003

data_manager:
  sources:
    links:
      input_lists:
        - examples/deployments/basic-ollama/miscellanea.list
  embedding_name: HuggingFaceEmbeddings

a2rchi:
  pipelines:
    - QAPipeline
  pipeline_map:
    QAPipeline:
      prompts:
        required:
          condense_prompt: examples/deployments/basic-ollama/condense.prompt
          chat_prompt: examples/deployments/basic-ollama/qa.prompt
      models:
        required:
          chat_model: OllamaInterface
          condense_model: OllamaInterface
  model_class_map:
    OllamaInterface:
      kwargs:
        url: http://localhost:7870 # make sure this matches your ollama server URL!
        base_model: "gemma3" # make sure this matches a model you have downloaded locally with ollama
