site_name: A2rchi Docs
nav:
  - Home: index.md
  - User Guide: user_guide.md
  - Developer Guide: developer_guide.md
  - About: about.md
theme: readthedocs
repo_url: https://github.com/mit-submit/A2rchi
repo_name: 'GitHub'
extra:
  version: 1.1.0
