name: PR Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: pr-preview-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  preview:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    env:
      A2RCHI_DIR: /home/runner/work/a2rchi-local
      HOME: /home/runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install a2rchi CLI
        run: |
          python -m pip install --upgrade pip
          pip install ".[all]" || pip install .

      - name: Verify MkDocs build
        run: mkdocs build --config-file docs/mkdocs.yml --strict

      - name: Run smoke deployment
        uses: ./.github/actions/run-smoke
        with:
          deployment-name: manual-${{ github.run_id }}
          config-path: tests/pr_preview_config/pr_preview_config.yaml
          config-destination: configs/ci/ci_config.yaml
          env-file: .env
          services: chatbot
          hostmode: "true"
          wait-url: http://localhost:7861/api/health
          base-url: http://localhost:7861
